typography_spectrum: 0.0786
color:
  brandColors:
    - '#bcbe7f'
    - '#a3754b'
    - '#5a2f2f'
    - '#757251'
    - '#290f1d'
  brandStrength: 0.2255164936650544
  lightness: 0.9081238938961178
  saturation: 0.9856278125662357
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5499351457692683
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: The Old Workhouse
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://www.twitter.com/theoldworkhouse'
    url: 'http://www.twitter.com/theoldworkhouse'
    name: Twitter
    type: external
  - id: 'http://www.facebook.com/theoldworkhousetv'
    url: 'http://www.facebook.com/theoldworkhousetv'
    name: Facebook
    type: external
  - id: 'http://www.tinyurl.com/theoldworkhouse'
    url: 'http://www.tinyurl.com/theoldworkhouse'
    name: YouTube
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: '"Home of the wretched poor"'
purpose: []
