typography_spectrum: 0.25691151223145425
content_rating:
  adult: false
color:
  brandColors:
    - '#bcbe7f'
    - '#a3754b'
    - '#5a2f2f'
    - '#757251'
    - '#290f1d'
  brandStrength: 0.2255164936650544
  lightness: 0.9081238938961178
  saturation: 0.9856278125662357
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7239105999469757
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/698ed79d-d6ad-4a9e-ace2-dceeb8dbe2e7.gif
name: The Old Workhouse
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://www.tinyurl.com/theoldworkhouse'
    url: 'http://www.tinyurl.com/theoldworkhouse'
    name: YouTube
    type: external
  - id: 'http://www.twitter.com/theoldworkhouse'
    url: 'http://www.twitter.com/theoldworkhouse'
    name: Twitter
    type: external
  - id: 'http://www.facebook.com/theoldworkhousetv'
    url: 'http://www.facebook.com/theoldworkhousetv'
    name: Facebook
    type: external
  - id: 'http://www.patreon.com/theoldworkhouse'
    url: 'http://www.patreon.com/theoldworkhouse'
    name: Patreon
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0923cc1b-ac11-4e04-a144-efd09b7d8bd2.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Old Workhouse - Home of the wretched poor
purpose: []
