name: The Old Workhouse
favicon: null
layout_spectrum: 0.93459
typography_spectrum: 0.31143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcbe7f'
    - '#a3754b'
    - '#5a2f2f'
    - '#757251'
    - '#290f1d'
  brandStrength: 0.22551649366505444
  lightness: 0.9081238938961178
  saturation: 0.9856278125662357
  rhythmicContrast: 0.5
purpose: []
