title: The Old Workhouse
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Home of the wretched poor
color:
  saturation: 0.9856278125662357
  brandStrength: 1
  lightness: 0.9081238938961178
  brandColors:
    - '#bcbe7f'
    - '#a3754b'
    - '#5a2f2f'
    - '#757251'
    - '#290f1d'
  rhythmicContrast: 0.5
navigation:
  - name: YouTube
    url: 'http://www.tinyurl.com/theoldworkhouse'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/theoldworkhouse'
    type: external
  - name: Facebook
    url: 'http://www.facebook.com/theoldworkhousetv'
    type: external
  - name: Patreon
    url: 'http://www.patreon.com/theoldworkhouse'
    type: external
cta:
  bucket: null
  version: null
  domain: null
name: The Old Workhouse
author:
  email: governor@TheOldWorkhouse.TV
  name: Adam Roxby
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0923cc1b-ac11-4e04-a144-efd09b7d8bd2.gif
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/698ed79d-d6ad-4a9e-ace2-dceeb8dbe2e7.gif
typography_spectrum: 0.09318996
layout_spectrum: 0.5537634
content_rating:
  adult: false
